Greeting.create(message: "Hello!")
Greeting.create(message: "How are you?")
Greeting.create(message: "Hope you doing well!")
Greeting.create(message: "good day!")
Greeting.create(message: "I am fine, thank you.")
Greeting.create(message: "Welcome to this website.")
